### ISSUE TITLE
Issues in getting job feed (application/atom+xml)

### ISSUE THREAD

**Issue by HemantPawar** [hasgeek/hasjob#202]
There are two issues:

- For any webpage `https://hasjob.co/example.com` website is providing `https://hasjob.co/at/%3CDomain%20example.com%3E/feed` feed url. Expected url is `https://hasjob.co/at/example.com/feed`

- `https://hasjob.co/at/example.com/feed"` still displays truncated/incomplete result.

**Comment by jace** [comment]
Fixed in 0b7f355 and 6c86e72.

1. We had forgotten to change the feed's URL when moving domain URL from `/at/<domain>` to `/<domain>`.
2. Feed content for all feeds was limited to 24 hours instead of 30 days because the index page is now >700 entries each month. I've changed it to instead carry the text of the last 100 entries (about 2-3 days worth of content on the home page).

**Comment by HemantPawar** [comment]
`at` is removed from url but first issue is still unresolved. It's showing `https://hasjob.co/%3CDomain%20example.com%3E/feed` instead of `https://hasjob.co/example.com/feed`

For example got to `https://hasjob.co/zigzobs.com` and type `document.getElementsByTagName("link")[14].href` in browser console.

**Comment by jace** [comment]
Good catch. Fixed in bbf8d1c.
